# Generated by Django 4.1.6 on 2023-02-16 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.CreateModel(
            name='IngredientsInReciepe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Количество ингредиента', verbose_name='Количество')),
                ('ingredient', models.ForeignKey(help_text='Ингредиенты', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.ingredient', verbose_name='Иншредиент')),
            ],
            options={
                'verbose_name': 'Ингредиент в рецепте',
                'verbose_name_plural': 'Ингредиенты в рецепте',
            },
        ),
        migrations.AlterField(
            model_name='reciepe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='recipes.ingredientsinreciepe'),
        ),
    ]
