# Generated by Django 4.1.6 on 2023-02-23 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='quantity',
            field=models.FloatField(help_text='Количество ингредиента', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
        migrations.AddConstraint(
            model_name='ingredientamount',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0.0)), name='quantity is non-negative'),
        ),
    ]
