# Generated by Django 4.1.6 on 2023-02-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredientamount_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciepe',
            old_name='tag',
            new_name='tags',
        ),
    ]
