# Generated by Django 4.1.6 on 2023-02-16 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinreciepe',
            name='ingredient',
            field=models.ForeignKey(help_text='Ингредиенты', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
    ]
