# Generated by Django 4.1.6 on 2023-02-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_tag_reciepe_tags'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientamount',
            name='quantity is non-negative',
        ),
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ForeignKey(help_text='Ингредиенты', on_delete=django.db.models.deletion.CASCADE, related_name='ingredienting', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='reciepe',
            field=models.ForeignKey(help_text='Рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='ingredientrec', to='recipes.reciepe', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='ingredientamount',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0.0)), name='amount is non-negative'),
        ),
    ]
