# Generated by Django 4.1.6 on 2023-02-26 17:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_alter_ingredientamount_ingredient_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciepe',
            name='cooking_time',
            field=models.IntegerField(help_text='Время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления'),
        ),
        migrations.CreateModel(
            name='ShoppingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adding_dt', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(help_text='Рецепт в список покупок', on_delete=django.db.models.deletion.CASCADE, related_name='in_shoppingcard', to='recipes.reciepe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(help_text='Пользователь, добавивший рецепт в список покупок', on_delete=django.db.models.deletion.CASCADE, related_name='in_shoppincard_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Список покупок',
                'ordering': ['-adding_dt'],
                'unique_together': {('user', 'recipe')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adding_dt', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(help_text='Рецепт в избранном', on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='recipes.reciepe', verbose_name='Рецепт')),
                ('user', models.ForeignKey(help_text='Пользователь, добавивший рецепт в избранное', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ['-adding_dt'],
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
